% -------------------------------------------------------------------------
% EXAMPLE: ROCKET Propellants
%
% Compute adiabatic temperature and equilibrium composition at constant
% pressure (e.g., 1.01325 bar) for lean to rich LH2-LOX mixtures at
% standard conditions, a set of 76 species considered and a set of
% equivalence ratios phi contained in (2, 8) [-]
%   
% HC/O2/N2 PROPELLANTS == {'CO2','CO','H2O','H2','O2','N2','He','Ar',...
%                'Cbgrb','C2','C2H','C2H2_acetylene','C2H2_vinylidene',...
%                'C2H3_vinyl','C2H4','C2H5','C2H5OH','C2H6',...
%                'C2N2','C2O','C3','C3H3_1_propynl',...
%                'C3H3_2_propynl','C3H4_allene','C3H4_propyne',...
%                'C3H5_allyl','C3H6O_acetone','C3H6_propylene',...
%                'C3H8','C4','C4H2_butadiyne','C5','C6H2','C6H6',...
%                'C8H18_isooctane','CH','CH2','CH2CO_ketene',...
%                'CH2OH','CH3','CH3CHO_ethanal','CH3CN',...
%                'CH3COOH','CH3O','CH3OH','CH4','CN','COOH','H',...
%                'H2O2','HCCO','HCHO_formaldehy','HCN','HCO',...
%                'HCOOH','HNC','HNCO','HNO','HO2','N','N2O',...
%                'NCO','NH','NH2','NH2OH','NH3','NO','NO2',...
%                'O','OCCN','OH','C3O2','C4N2','RP_1','H2bLb',...
%                'O2bLb'}
%   
% See wiki or ListSpecies() for more predefined sets of species
%
% @author: Alberto Cuadra Lara
%          PhD Candidate - Group Fluid Mechanics
%          Universidad Carlos III de Madrid
%                 
% Last update April 05 2022
% -------------------------------------------------------------------------

%% INITIALIZE
self = App('HC/O2/N2 PROPELLANTS');
%% INITIAL CONDITIONS
self = set_prop(self, 'TR', 250, 'pR', 1 * 1.01325, 'phi', 0.5:0.1:4);
self.PD.S_Fuel     = {'RP_1'};
self.PD.S_Oxidizer = {'O2bLb'};
%% SOLVE PROBLEM
self = SolveProblem(self, 'ROCKET');
%% DISPLAY RESULTS (PLOTS)
postResults(self);