% -------------------------------------------------------------------------
% EXAMPLE: SHOCK_I_IONIZATION
%
% Compute pre-shock and post-shock state for a planar incident shock wave
% at standard conditions, a set of 51 species considered and a set of
% initial shock front velocities (u1) contained in (360, 13000) [m/s]
%    
% Air_ions == {'eminus', 'Ar', 'Arplus', 'C', 'Cplus', 'Cminus', ...
%              'CN', 'CNplus', 'CNminus', 'CNN', 'CO', 'COplus', ...
%              'CO2', 'CO2plus', 'C2', 'C2plus', 'C2minus', 'CCN', ...
%              'CNC', 'OCCN', 'C2N2', 'C2O', 'C3', 'C3O2', 'N', ...
%              'Nplus', 'Nminus', 'NCO', 'NO', 'NOplus', 'NO2', ...
%              'NO2minus', 'NO3', 'NO3minus', 'N2', 'N2plus', ...
%              'N2minus', 'NCN', 'N2O', 'N2Oplus', 'N2O3', 'N2O4', ...
%              'N2O5', 'N3', 'O', 'Oplus', 'Ominus', 'O2', 'O2plus', ...
%              'O2minus', 'O3'}
%   
% See wiki or list_species() for more predefined sets of species
%
% @author: Alberto Cuadra Lara
%          PhD Candidate - Group Fluid Mechanics
%          Universidad Carlos III de Madrid
%                 
% Last update Jan 10 2023
% -------------------------------------------------------------------------

% Air_ions = {'O2','N2','O','O3','N','NO','NO2','NO3','N2O','N2O3',...
%              'N2O4','N3_M','eminus','Nminus','Nplus','NOplus','NO2minus_M',...
%              'NO3minus_M','N2plus','N2minus','N2Oplus','Oplus','Ominus',...
%              'O2plus', 'O2minus','CO2','CO','COplus','C','Cplus',...
%              'Cminus','CN_M','CNplus_M','CNminus_M','CNN_M','NCO','NCN_M','Ar',...
%              'Arplus','O2_M','O3_M','CO2_M','O3minus_M','O3plus_M',...
%              'N3minus_M','N3plus_M','NO3plus_M','CNminus_M','CNplus_M',...
%              'NCOminus_M','NCOplus_M','NCNminus_M','NCNplus_M','O4_M',...
%              'O4minus_M','O4plus_M'};

Air_ions = {'eminus', 'Ar', 'Arplus', 'C', 'Cplus', 'Cminus', ...
            'CN', 'CNplus', 'CNminus', 'CNN', 'CO', 'COplus', ...
            'CO2', 'CO2plus', 'C2', 'C2plus', 'C2minus', 'CCN', ...
            'CNC', 'OCCN', 'C2N2', 'C2O', 'C3', 'C3O2', 'N', ...
            'Nplus', 'Nminus', 'NCO', 'NO', 'NOplus', 'NO2', ...
            'NO2minus', 'NO3', 'NO3minus', 'N2', 'N2plus', ...
            'N2minus', 'NCN', 'N2O', 'N2Oplus', 'N2O3', 'N2O4', ...
            'N2O5', 'N3', 'O', 'Oplus', 'Ominus', 'O2', 'O2plus', ...
            'O2minus', 'O3'};

% Air_ions = find_species_LS(self.S.LS_DB, {'C','N','O','minus','plus','Ar'}, 'any',...
% {'I', 'S', 'L', 'T', 'P', 'F', 'ab', 'W', 'Z','X','R','Os','Cr','H','Br',...
% 'G','K','U','Co','Cu','B','V','Ni','Na','Mg','Mo','Ag','Nb','Cb','Cl','D','T',...
% 'Ca','Cs','Ne','Cd','Mn'}, 'all');

%% INITIALIZE
self = App(Air_ions);
self.TN.FLAG_TCHEM_FROZEN = false;
%% INITIAL CONDITIONS
self = set_prop(self, 'TR', 300, 'pR', 1 * 1.01325);
self.PD.S_Oxidizer = {'N2', 'O2', 'Ar', 'CO2'};
self.PD.N_Oxidizer = [3.7276, 1.0000, 0.0447, 0.0015];
sound_velocity = compute_sound(self.PD.TR.value, self.PD.pR.value, self.PD.S_Oxidizer, self.PD.N_Oxidizer, 'self', self);
%% ADDITIONAL INPUTS (DEPENDS OF THE PROBLEM SELECTED)
u1 = logspace(2, 5, 500); u1 = u1(u1<20000); u1 = u1(u1 >= 1 * sound_velocity);
self = set_prop(self, 'u1', u1);
%% SOLVE PROBLEM
self = solve_problem(self, 'SHOCK_I');
%% DISPLAY RESULTS (PLOTS)
post_results(self);

% ax = set_figure;
% plot_figure('Pressure', cell2vector(self.PS.strP, 'p'), 'dVdT_p', cell2vector(self.PS.strP, 'dVdT_p'), 'ax', ax);
% ax = set_figure;
% plot_figure('Temperature', cell2vector(self.PS.strP, 'T'), 'Ngas', cell2vector(self.PS.strP, 'N'), 'ax', ax);
% ax = set_figure;
% plot_figure('Temperature', cell2vector(self.PS.strP, 'T'), 'p', cell2vector(self.PS.strP, 'p'), 'ax', ax);
% ax = set_figure;
% plot_figure('Temperature', cell2vector(self.PS.strP, 'T'), 'W', cell2vector(self.PS.strP, 'W'), 'ax', ax);
% ax = set_figure;
% plot_figure('Temperature', cell2vector(self.PS.strP, 'T'), 'rho', cell2vector(self.PS.strP, 'rho'), 'ax', ax);